name: send mail
on: push

jobs:
  sending_mail:
    runs-on: ubuntu-latest

    steps:
    - name: print hello world
      run: echo "Hello world"

    - name: Sending the mail
      if: ${{ always() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Sending For You
        body: Hello, Hansel
        to: intern_2@arizonsystems.com
        from: ${{ secrets.EMAIL_USERNAME }}
